package com.googoo.invitation.domain.enum

enum class Bank(val value: String) {
    NH("NH농협")
    , KAKAO("카카오뱅크")
    , KB("KB국민")
    , SHINHAN("신한")
    , WOORI("우리")
    , TOSS("토스뱅크")
    , IBK("IBK기업")
    , HANA("하나")
    , MG("새마을")
    , BUSAN("부산")
    , DGB("대구")
    , KBANK("케이뱅크")
    , CU("신협")
    , POST("우체국")
    , SC("SC제일")
    , BNK("경남")
    , GWANGJU("광주")
    , SUHYUP("수협")
    , JEONBUK("전북")
    , SB("저축은행")
    , JEJU("제주")
    , CITY("씨티")
    , KDB("KDB산업")
    , FOREST("산림조합")
    , SBI("SBI저축은행")
    , CUSTOM("직접입력")
}